<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SistemaOroAmbiental.DataBaseScripts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Scripts\**\*.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
